%% AeroCortex MATLAB Digital Twin Telemetry Interface
% Streams 6-DOF UAV state bus to AeroCortex Local Edge API and applies recovery commands.
% Compatible with MATLAB R2022b through R2025b+.

clear; clc;
fprintf('=== AeroCortex UAV MATLAB Digital Twin Interface ===\n');

api_url = 'http://127.0.0.1:8000/telemetry';
webopts = weboptions(...
    'MediaType', 'application/json', ...
    'Timeout', 5, ...
    'RequestMethod', 'post' ...
);

% Flight simulation parameters
dt = 0.5;           % 500ms time step
num_steps = 40;     % Total trajectory steps

% Base UAV Initial State
uav_packet = struct(...
    'timestamp', posixtime(datetime('now')), ...
    'mission_id', 'MATLAB_MISSION_001', ...
    'latitude', 11.0168, ...
    'longitude', 76.9558, ...
    'altitude', 120.0, ...
    'velocity', 12.5, ...
    'battery_level', 92.0, ...
    'battery_voltage', 16.2, ...
    'gps_status', 'healthy', ...
    'gps_accuracy', 1.4, ...
    'imu_acceleration', [0.0, 0.0, 9.81], ...
    'imu_gyroscope', [0.0, 0.0, 0.0], ...
    'wind_speed', 6.8, ...
    'wind_direction', 180.0, ...
    'communication_status', 'connected', ...
    'mission_state', 'CRUISE', ...
    'waypoint', 1, ...
    'heading', 90.0, ...
    'payload_status', 'nominal' ...
);

fprintf('Streaming telemetry to AeroCortex API at: %s\n\n', api_url);

for step = 1:num_steps
    % Advance time and battery
    uav_packet.timestamp = posixtime(datetime('now'));
    uav_packet.battery_level = max(0.0, uav_packet.battery_level - 0.15);
    uav_packet.battery_voltage = 13.6 + (uav_packet.battery_level / 100.0) * 3.2;
    uav_packet.waypoint = floor(step / 10) + 1;
    
    % Inject GPS Interference Failure at step 15
    if step == 15
        fprintf('\n>>> [MATLAB FAULT INJECTION] Triggering GPS Multipath Interference! <<<\n\n');
        uav_packet.gps_status = 'degraded';
        uav_packet.gps_accuracy = 6.8;
    end
    
    try
        % POST Telemetry to AeroCortex Gateway
        response = webwrite(api_url, uav_packet, webopts);
        
        % Extract cognitive recovery verdict
        action = response.action;
        approved = response.is_approved;
        status = response.execution_status;
        
        fprintf('Step %02d | Bat: %.1f%% | GPS: %s (HDOP: %.1f) -> Action: [%s] (Approved: %d)\n', ...
            step, uav_packet.battery_level, uav_packet.gps_status, uav_packet.gps_accuracy, ...
            action, approved);
            
    catch ME
        fprintf('Step %02d | Failed to connect to AeroCortex API: %s\n', step, ME.message);
        fprintf('         (Ensure AeroCortex API is running: python main.py --api)\n');
        break;
    end
    
    pause(0.2); % Simulation loop pacing
end

fprintf('\n=== MATLAB Mission Simulation Concluded ===\n');
